### 1. Post a message as User 1
POST http://localhost:5206/chatlog
Content-Type: application/json 

{
    "Message" : "Hello from User One!",
    "UserId": 1
}

### 2. Post a message as User 2
POST http://localhost:5206/chatlog
Content-Type: application/json 

{
    "Message" : "MeowMan",
    "UserId": 2
}

### 3. Get ALL messages in the database
GET http://localhost:5206/chatlog

### 4. Filter: Get ONLY User 2's messages
GET http://localhost:5206/chatlog?userId=2

### 5. edit Message 1 (Should work fine)
PUT http://localhost:5206/chatlog/1
Content-Type: application/json

{
    "NewMessage": "This message has been edited!"
}

### 6. Try to delete Message 2 (Should fail with 403 Forbidden!)
### (Because our DELETE code checks if UserId == 1, but Message 2 belongs to User 2)
DELETE http://localhost:5206/chatlog/5/2

### 7. Try to delete Message 1 (Should succeed with 204 No Content)
DELETE http://localhost:5206/chatlog/1